sudo: false
language: rust
rust:
- stable
- 1.8.0
- beta
- nightly
branches:
  except:
  - gh-pages
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo --only stable doc
after_success:
- travis-cargo --only stable doc-upload
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - secure: Fh2K3TJirRTS4S31myR9dIlo9HlbZLaq0dFh7GSPwjG1VgM6VOn47uoOh0Uhdj39mnVNh1xeby20oPYbtSaZjRUBPpaQijzlmxkEoc0aP1j4NysFJdD5Z+aUKJznf+Y7z9w/ZkVsJalmDEYCbpcfWNPYWpGtpOnio5q18pfB5LGX/wPK44h2p/gsxAvuqAHeRNnajx6Kh9sZxJaLxBJekpwwAJT37vASZR0WZeRwedRX8OYayZEmVlwzuWKoe+7ACFicRUZK39O1W9lV5qFRNccyBAp2m3JMLXJDnVYU7TtRUL/bZMUESBMuFYqGayScTGPcXOIk6vKiOR8JsHQgEOy4R8m+MEbqlv5ryyinhWc+94eXgJP6MkHxsAhKIXbSB+OvCN/mvGo4NuqzZQfC3LbH98A3oXpvuUe477q02HabLLYqzUIMgqvmB7td693NQCBU5/Af/gT2S4pvkgM/Ieiiz3S+eVhLen7o9G22IMLCeUmuqKxI5AIRzFZf0i8y58qLY2OwGQQtVI2KkbrvCHZPIe/jQSKJ6EAR67G+4ro9+5KP/tYU3dsclymEUYu0gz6cB69DK4rD50P1WzNMBVWI5ozkE4HNFP0DWfqFPGLDbbufpRPOpXdioweRJ0MqpXlbpaWvCk+Xp6xLdXapW4ViGyLDdEkQr9QGGDQzMow=
