[package]
name = "widestring"
version = "0.1.0"
authors = ["Kathryn Long <squeeself@gmail.com>"]
description = "A wide string FFI library for converting to and from Windows Wide \"Unicode\" strings."
repository = "https://github.com/starkat99/widestring-rs.git"
homepage = "https://github.com/starkat99/widestring-rs"
readme = "README.md"
keywords = ["windows", "wide", "string", "win32"]
license = "MIT/Apache-2.0"
