[package]
name = "widestring"
version = "0.2.2"
authors = ["Kathryn Long <squeeself@gmail.com>"]
description = "A wide string FFI library for converting to and from Wide \"Unicode\" (UTF-16) strings, such as those often used in Windows API."
repository = "https://github.com/starkat99/widestring-rs.git"
readme = "README.md"
keywords = ["windows", "wide", "string", "win32", "utf16"]
license = "MIT/Apache-2.0"

[dev-dependencies]
winapi = { version = "0.3", features = ["winbase"] }